var express = require('express');
var ctrAlunos = require('../controllers/AlunoController');
var ctrDisciplinas = require('../controllers/DisciplinaController');
var ctrCursos = require('../controllers/CursoController');
var ctrTurmas = require('../controllers/TurmaController');
var ctrHistoricos = require('../controllers/HistoricoController');
var router = express.Router();
router.get('/aluno', ctrAlunos.findAll);
router.get('/aluno/:aluno_id', ctrAlunos.findOne);
router.post('/aluno', ctrAlunos.create);
router.get('/disciplina', ctrDisciplinas.findAll);
router.get('/disciplina/:disciplina_id', ctrDisciplinas.findOne);
router.post('/disciplina', ctrDisciplinas.create);
router.post('/disciplina/adicionar-curso', ctrDisciplinas.adicionarCurso);
router.post('/disciplina/adicionar-disciplina-requisito', ctrDisciplinas.adicionarDisciplinaRequisito);
router.get('/curso', ctrCursos.findAll);
router.get('/curso/:curso_id', ctrCursos.findOne);
router.post('/curso', ctrCursos.create);
router.get('/turma', ctrTurmas.findAll);
router.get('/turma/:turma_id', ctrTurmas.findOne);
router.post('/turma', ctrTurmas.create);
router.get('/historico', ctrHistoricos.findAll);
router.get('/historico/:historico_id', ctrHistoricos.findOne);
router.post('/historico', ctrHistoricos.create);
module.exports = router;